import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'config.dart';
import 'services/api_service.dart';

const maroon=Color(0xFF8C1119), cream=Color(0xFFFCFAF5), gold=Color(0xFFC8A45A), muted=Color(0xFF82909A);

void main()=>runApp(const ConferenceApp());
class ConferenceApp extends StatelessWidget{const ConferenceApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:conferenceName,theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:cream,colorScheme:ColorScheme.fromSeed(seedColor:maroon),fontFamily:'Arial'),home:const AuthGate());}

class AuthGate extends StatefulWidget{const AuthGate({super.key});@override State<AuthGate> createState()=>_AuthGateState();}
class _AuthGateState extends State<AuthGate>{bool loading=true,logged=false;@override void initState(){super.initState();_check();}Future<void>_check()async{final p=await SharedPreferences.getInstance();setState((){logged=p.getString('token')!=null;loading=false;});} @override Widget build(BuildContext c)=>loading?const Scaffold(body:Center(child:CircularProgressIndicator())):logged?const MainShell():LoginScreen(onLogin:()=>setState(()=>logged=true));}

class LoginScreen extends StatefulWidget{final VoidCallback onLogin;const LoginScreen({super.key,required this.onLogin});@override State<LoginScreen> createState()=>_LoginScreenState();}
class _LoginScreenState extends State<LoginScreen>{final e=TextEditingController(text:'participant@conference.local'),p=TextEditingController(text:'Demo@123');bool busy=false,obscure=true;Future<void>login()async{setState(()=>busy=true);try{final r=await ApiService.login(e.text.trim(),p.text);final sp=await SharedPreferences.getInstance();await sp.setString('token',r['token']);await sp.setString('name',r['user']['name']);widget.onLogin();}catch(x){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x.toString())));}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SizedBox(height:40),Container(height:130,decoration:BoxDecoration(color:maroon,borderRadius:BorderRadius.circular(28)),child:const Center(child:Icon(Icons.event_available,size:72,color:Colors.white))),const SizedBox(height:28),Text(conferenceName,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800,color:maroon)),const SizedBox(height:8),const Text('Secure conference access for delegates, speakers and teams.',style:TextStyle(color:muted,fontSize:16)),const SizedBox(height:28),TextField(controller:e,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email',prefixIcon:Icon(Icons.email_outlined),border:OutlineInputBorder())),const SizedBox(height:14),TextField(controller:p,obscureText:obscure,decoration:InputDecoration(labelText:'Password',prefixIcon:const Icon(Icons.lock_outline),suffixIcon:IconButton(onPressed:()=>setState(()=>obscure=!obscure),icon:Icon(obscure?Icons.visibility:Icons.visibility_off)),border:const OutlineInputBorder())),const SizedBox(height:20),FilledButton(style:FilledButton.styleFrom(backgroundColor:maroon,padding:const EdgeInsets.symmetric(vertical:16)),onPressed:busy?null:login,child:busy?const CircularProgressIndicator(color:Colors.white):const Text('Sign In')),const SizedBox(height:12),const Text('Demo: participant@conference.local / Demo@123',textAlign:TextAlign.center,style:TextStyle(color:muted))]))));}

class MainShell extends StatefulWidget{const MainShell({super.key});@override State<MainShell> createState()=>_MainShellState();}
class _MainShellState extends State<MainShell>{int i=0;final pages=const[HomeScreen(),ScheduleScreen(),ChatScreen(),NoticesScreen(),GalleryScreen(),ProfileScreen()];@override Widget build(BuildContext c)=>Scaffold(body:pages[i],bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(x)=>setState(()=>i=x),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.calendar_month_outlined),selectedIcon:Icon(Icons.calendar_month),label:'Schedule'),NavigationDestination(icon:Icon(Icons.chat_bubble_outline),selectedIcon:Icon(Icons.chat_bubble),label:'Chat'),NavigationDestination(icon:Icon(Icons.notifications_none),selectedIcon:Icon(Icons.notifications),label:'Notices'),NavigationDestination(icon:Icon(Icons.photo_library_outlined),selectedIcon:Icon(Icons.photo_library),label:'Gallery'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')]));}

class Header extends StatelessWidget{final String title;const Header({super.key,this.title='Home'});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.fromLTRB(22,46,22,22),decoration:const BoxDecoration(color:maroon,borderRadius:BorderRadius.vertical(bottom:Radius.circular(30))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const CircleAvatar(radius:24,backgroundColor:Colors.white,child:Icon(Icons.account_balance,color:maroon)),const Spacer(),Container(padding:const EdgeInsets.symmetric(horizontal:12,vertical:8),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(10)),child:const Text('DPU',style:TextStyle(color:maroon,fontWeight:FontWeight.w900,fontSize:22)))]),const SizedBox(height:12),const Text(conferenceShort,style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w800)),const SizedBox(height:6),Text(title,style:const TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w600))]));}

class CardButton extends StatelessWidget{final IconData icon;final String title,subtitle;final VoidCallback onTap;const CardButton({super.key,required this.icon,required this.title,required this.subtitle,required this.onTap});@override Widget build(BuildContext c)=>Card(elevation:0,margin:const EdgeInsets.only(bottom:14),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20)),child:InkWell(borderRadius:BorderRadius.circular(20),onTap:onTap,child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[Container(width:54,height:54,decoration:BoxDecoration(color:maroon.withOpacity(.07),borderRadius:BorderRadius.circular(16)),child:Icon(icon,color:maroon)),const SizedBox(width:16),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(subtitle,style:const TextStyle(color:muted))])),const Icon(Icons.arrow_forward_ios,size:16,color:gold)]))));}

class HomeScreen extends StatelessWidget{const HomeScreen({super.key});void go(BuildContext c,Widget w)=>Navigator.push(c,MaterialPageRoute(builder:(_)=>w));@override Widget build(BuildContext c)=>SafeArea(top:false,child:SingleChildScrollView(child:Column(children:[const Header(),Padding(padding:const EdgeInsets.fromLTRB(20,24,20,90),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Welcome to the Conference',style:TextStyle(fontSize:26,fontWeight:FontWeight.w900,color:maroon)),const SizedBox(height:6),const Text('100th AIU Annual General Body Meet & National Conference of Vice Chancellors',style:TextStyle(fontSize:16,fontWeight:FontWeight.w600)),const SizedBox(height:24),const Text('ESSENTIAL INFO',style:TextStyle(letterSpacing:1.5,color:maroon,fontWeight:FontWeight.w900)),const SizedBox(height:12),CardButton(icon:Icons.groups,title:'Conference Speakers',subtitle:'Distinguished speakers & profiles',onTap:()=>go(c,const SpeakersScreen())),CardButton(icon:Icons.calendar_month,title:'Event Schedule',subtitle:'Detailed session timeline',onTap:()=>go(c,const ScheduleScreen())),CardButton(icon:Icons.location_on,title:'Directions & Venue',subtitle:'Open conference location in Maps',onTap:()=>launchUrl(Uri.parse(mapUrl),mode:LaunchMode.externalApplication)),CardButton(icon:Icons.hotel,title:'My Accommodation',subtitle:'Hotel, room and check-in details',onTap:()=>go(c,const AccommodationScreen())),CardButton(icon:Icons.directions_car,title:'Transport',subtitle:'Pickup, vehicle and driver details',onTap:()=>go(c,const TransportScreen())),CardButton(icon:Icons.assignment,title:'Duty Roster',subtitle:'Your assigned conference duties',onTap:()=>go(c,const DutiesScreen())),CardButton(icon:Icons.qr_code_2,title:'Digital ID / QR',subtitle:'Registration pass and QR code',onTap:()=>go(c,const DigitalIdScreen())),CardButton(icon:Icons.fact_check,title:'Attendance',subtitle:'Your session attendance history',onTap:()=>go(c,const AttendanceScreen())),CardButton(icon:Icons.workspace_premium,title:'Certificate',subtitle:'View and download certificate',onTap:()=>go(c,const CertificateScreen())),CardButton(icon:Icons.restaurant,title:'Meals',subtitle:'Breakfast, lunch, tea and dinner',onTap:()=>go(c,const MealsScreen())),CardButton(icon:Icons.emergency,title:'Emergency Help',subtitle:'Medical, security and help desk',onTap:()=>go(c,const EmergencyScreen()))]))]));}

class ScheduleScreen extends StatefulWidget{const ScheduleScreen({super.key});@override State<ScheduleScreen> createState()=>_ScheduleScreenState();}
class _ScheduleScreenState extends State<ScheduleScreen>{Future<List<dynamic>> load()=>ApiService.get('/sessions?conferenceId=1');@override Widget build(BuildContext c)=>SafeArea(top:false,child:Column(children:[const Header(title:'Event Schedule'),Expanded(child:FutureBuilder(future:load(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('Unable to load schedule'));final data=s.data as List;return ListView.builder(padding:const EdgeInsets.all(18),itemCount:data.length,itemBuilder:(c,i){final x=data[i];return Card(margin:const EdgeInsets.only(bottom:12),child:ListTile(contentPadding:const EdgeInsets.all(16),leading:CircleAvatar(backgroundColor:maroon.withOpacity(.08),child:const Icon(Icons.event,color:maroon)),title:Text(x['title']??'',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x['session_date']} • ${x['start_time']} - ${x['end_time']}\n${x['speaker_name']??'Speaker'} • ${x['hall_name']??'Hall'}'),isThreeLine:true,trailing:IconButton(icon:const Icon(Icons.star_border),onPressed:()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Session saved')))));});}))]));}

class SpeakersScreen extends StatelessWidget{const SpeakersScreen({super.key});@override Widget build(BuildContext c)=>SimplePage(title:'Speakers',future:ApiService.get('/speakers?conferenceId=1'),builder:(x)=>ListTile(leading:CircleAvatar(backgroundImage:x['photo']!=null?NetworkImage(x['photo']):null,child:x['photo']==null?const Icon(Icons.person):null),title:Text(x['name']??'',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x['designation']??''}\n${x['organization']??''}'),isThreeLine:true));}

class NoticesScreen extends StatelessWidget{const NoticesScreen({super.key});@override Widget build(BuildContext c)=>SafeArea(top:false,child:Column(children:[const Header(title:'Notices'),Expanded(child:FutureBuilder(future:ApiService.get('/notices?conferenceId=1'),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load notices'));final d=s.data as List;return d.isEmpty?const Center(child:Text('No Notices',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800))):ListView.builder(padding:const EdgeInsets.all(18),itemCount:d.length,itemBuilder:(c,i)=>Card(child:ListTile(leading:const Icon(Icons.notifications,color:maroon),title:Text(d[i]['title']??'',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(d[i]['message']??''))))}))]));}

class GalleryScreen extends StatelessWidget{const GalleryScreen({super.key});@override Widget build(BuildContext c)=>SafeArea(top:false,child:Column(children:[const Header(title:'Event Gallery'),Expanded(child:FutureBuilder(future:ApiService.get('/gallery?conferenceId=1'),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load gallery'));final d=s.data as List;return GridView.builder(padding:const EdgeInsets.all(10),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:8,mainAxisSpacing:8),itemCount:d.length,itemBuilder:(c,i)=>ClipRRect(borderRadius:BorderRadius.circular(14),child:Image.network(d[i]['url'],fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:Colors.grey.shade200,child:const Icon(Icons.image)))));} ))]));}

class ChatScreen extends StatelessWidget{const ChatScreen({super.key});@override Widget build(BuildContext c)=>SafeArea(top:false,child:Column(children:[const Header(title:'Messages'),Expanded(child:ListView(padding:const EdgeInsets.all(18),children:[CardButton(icon:Icons.person,title:'Dr. Pallavi Kiran Shinde',subtitle:'Conference Liaison Faculty • Chat with your liaison',onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ConversationScreen()))),const SizedBox(height:20),const Center(child:Text('Real-time chat is enabled by the backend Socket.IO layer.',style:TextStyle(color:muted)))]))]));}
class ConversationScreen extends StatefulWidget{const ConversationScreen({super.key});@override State<ConversationScreen> createState()=>_ConversationScreenState();}
class _ConversationScreenState extends State<ConversationScreen>{final t=TextEditingController();final messages=['Good morning! How can I help you?'];void send(){if(t.text.trim().isEmpty)return;setState((){messages.add(t.text.trim());t.clear();});} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Dr. Pallavi Kiran Shinde')),body:Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:messages.length,itemBuilder:(c,i)=>Align(alignment:i.isEven?Alignment.centerLeft:Alignment.centerRight,child:Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:i.isEven?Colors.white:maroon,borderRadius:BorderRadius.circular(16)),child:Text(messages[i],style:TextStyle(color:i.isEven?Colors.black:Colors.white))))),),Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:t,decoration:const InputDecoration(hintText:'Message...',border:OutlineInputBorder()))),IconButton(onPressed:send,icon:const Icon(Icons.send,color:maroon))]))]));}

class ProfileScreen extends StatefulWidget{const ProfileScreen({super.key});@override State<ProfileScreen> createState()=>_ProfileScreenState();}
class _ProfileScreenState extends State<ProfileScreen>{Future<dynamic> load()=>ApiService.get('/me/profile');Future<void>logout()async{final p=await SharedPreferences.getInstance();await p.clear();if(mounted)Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder:(_)=>const AuthGate()),(_)=>false);} @override Widget build(BuildContext c)=>SafeArea(top:false,child:Column(children:[const Header(title:'My Profile'),Expanded(child:FutureBuilder(future:load(),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load profile'));final x=s.data;return ListView(padding:const EdgeInsets.fromLTRB(20,20,20,90),children:[CircleAvatar(radius:48,backgroundImage:x['photo']!=null?NetworkImage(x['photo']):null,child:x['photo']==null?const Icon(Icons.person,size:48):null),const SizedBox(height:14),Text(x['name']??'',textAlign:TextAlign.center,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),Text(x['email']??'',textAlign:TextAlign.center,style:const TextStyle(color:muted)),const SizedBox(height:20),InfoSection(title:'BASIC INFORMATION',items:{'Role':x['role'],'Mobile No':x['phone'],'University':x['university'],'Designation':x['designation'],'Blood Group':x['blood_group'],'Registration No':x['registration_no']}),InfoSection(title:'ACCOMMODATION',items:{'Hotel':x['hotel_name'],'Room':x['room_number'],'Liaison':x['liaison_name'],'Liaison Phone':x['liaison_phone']}),InfoSection(title:'ARRIVAL DETAILS',items:{'Mode of Travel':x['mode_of_travel'],'Arrival Date':x['arrival_date'],'Arrival Time':x['arrival_time'],'Departure Date':x['departure_date'],'Departure Time':x['departure_time']}),OutlinedButton.icon(onPressed:logout,icon:const Icon(Icons.logout),label:const Text('Sign Out'))]);}))]));}
class InfoSection extends StatelessWidget{final String title;final Map<String,dynamic>items;const InfoSection({super.key,required this.title,required this.items});@override Widget build(BuildContext c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(letterSpacing:1.4,color:muted,fontWeight:FontWeight.w900)),const SizedBox(height:8),Card(child:Column(children:items.entries.map((e)=>ListTile(title:Text(e.key),trailing:SizedBox(width:170,child:Text('${e.value??'—'}',textAlign:TextAlign.right,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700)))).toList()))),const SizedBox(height:18)]);}

class AccommodationScreen extends StatelessWidget{const AccommodationScreen({super.key});@override Widget build(BuildContext c)=>DetailApiPage(title:'Your Accommodation',path:'/me/accommodation',icon:Icons.hotel,empty:'No room assigned',fields:['hotel_name','room_number','room_type','address','check_in','check_out']);}
class TransportScreen extends StatelessWidget{const TransportScreen({super.key});@override Widget build(BuildContext c)=>ListApiPage(title:'Transport',path:'/me/transport',icon:Icons.directions_car,fields:['pickup_location','drop_location','pickup_time','vehicle_number','vehicle_type','driver_name','driver_phone','status']);}
class DutiesScreen extends StatelessWidget{const DutiesScreen({super.key});@override Widget build(BuildContext c)=>ListApiPage(title:'Duty Roster',path:'/me/duties',icon:Icons.assignment,fields:['title','location','duty_date','start_time','end_time','supervisor','status']);}
class AttendanceScreen extends StatelessWidget{const AttendanceScreen({super.key});@override Widget build(BuildContext c)=>ListApiPage(title:'My Attendance',path:'/me/attendance',icon:Icons.fact_check,fields:['title','session_date','start_time','scan_type','scanned_at']);}
class MealsScreen extends StatelessWidget{const MealsScreen({super.key});@override Widget build(BuildContext c)=>StaticMeals();}
class StaticMeals extends StatelessWidget{const StaticMeals({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Meals')),body:ListView(padding:const EdgeInsets.all(18),children:const[Meal('Breakfast','07:00 – 09:00','Hyatt Regency',Icons.free_breakfast),Meal('Lunch','12:30 – 14:00','Conference Dining Hall',Icons.lunch_dining),Meal('High Tea','16:00 – 17:00','Foyer',Icons.local_cafe),Meal('Dinner','19:30 – 21:30','Hyatt Regency',Icons.dinner_dining)]));}
class Meal extends StatelessWidget{final String a,b,c;final IconData i;const Meal(this.a,this.b,this.c,this.i,{super.key});@override Widget build(BuildContext x)=>Card(child:ListTile(leading:Icon(i,color:maroon),title:Text(a,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('$b\n$c'),isThreeLine:true));}
class DigitalIdScreen extends StatelessWidget{const DigitalIdScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Digital Conference ID')),body:Center(child:FutureBuilder(future:ApiService.get('/me/registration'),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const CircularProgressIndicator();if(s.hasError)return const Text('Unable to load ID');final x=s.data;return Card(margin:const EdgeInsets.all(20),child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.account_balance,color:maroon,size:42),const SizedBox(height:10),const Text(conferenceShort,textAlign:TextAlign.center,style:TextStyle(color:maroon,fontWeight:FontWeight.w900,fontSize:20)),const SizedBox(height:20),Text(x['conference_name']??'',textAlign:TextAlign.center),const SizedBox(height:8),Text('Registration: ${x['registration_no']}',style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:18),QrImageView(data:x['qr_token']??x['registration_no']??'DPU-QR',size:190),const SizedBox(height:12),Text(x['category']??'',style:const TextStyle(color:muted))]))));}));}
class CertificateScreen extends StatelessWidget{const CertificateScreen({super.key});@override Widget build(BuildContext c)=>DetailApiPage(title:'Certificate',path:'/me/certificate',icon:Icons.workspace_premium,empty:'Certificate not issued yet',fields:['certificate_no','issued_at','certificate_url']);}
class EmergencyScreen extends StatelessWidget{const EmergencyScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Emergency & Help')),body:ListView(padding:const EdgeInsets.all(18),children:[CardButton(icon:Icons.support_agent,title:'Conference Help Desk',subtitle:'1800123456',onTap:()=>launchUrl(Uri.parse('tel:1800123456'))),CardButton(icon:Icons.local_hospital,title:'Medical Emergency',subtitle:'Call 108',onTap:()=>launchUrl(Uri.parse('tel:108'))),CardButton(icon:Icons.security,title:'Security',subtitle:'Call 100',onTap:()=>launchUrl(Uri.parse('tel:100'))),CardButton(icon:Icons.location_on,title:'Venue Map',subtitle:'Open in Google Maps',onTap:()=>launchUrl(Uri.parse(mapUrl),mode:LaunchMode.externalApplication))]));}

class SimplePage extends StatelessWidget{final String title;final Future future;final Widget Function(dynamic) builder;const SimplePage({super.key,required this.title,required this.future,required this.builder});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:FutureBuilder(future:future,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load data'));final d=s.data as List;return ListView.separated(padding:const EdgeInsets.all(18),itemCount:d.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(c,i)=>Card(child:builder(d[i]))); }));}
class DetailApiPage extends StatelessWidget{final String title,path,empty;final IconData icon;final List<String>fields;const DetailApiPage({super.key,required this.title,required this.path,required this.icon,required this.empty,required this.fields});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:FutureBuilder(future:ApiService.get(path),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load details'));if(s.data==null)return Center(child:Text(empty));final x=s.data;return ListView(padding:const EdgeInsets.all(18),children:[Card(child:Column(children:fields.map((f)=>ListTile(leading:Icon(icon,color:maroon),title:Text(f.replaceAll('_',' ').toUpperCase()),subtitle:Text('${x[f]??'—'}',style:const TextStyle(fontWeight:FontWeight.w700))).toList())))]); }));}
class ListApiPage extends StatelessWidget{final String title,path;final IconData icon;final List<String>fields;const ListApiPage({super.key,required this.title,required this.path,required this.icon,required this.fields});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:FutureBuilder(future:ApiService.get(path),builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return const Center(child:Text('Unable to load details'));final d=s.data as List;if(d.isEmpty)return const Center(child:Text('No records found'));return ListView.builder(padding:const EdgeInsets.all(18),itemCount:d.length,itemBuilder:(c,i)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:fields.map((f)=>ListTile(dense:true,leading:Icon(icon,color:maroon),title:Text(f.replaceAll('_',' ')),trailing:SizedBox(width:190,child:Text('${d[i][f]??'—'}',textAlign:TextAlign.right,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700))))).toList()))));}));}
