import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,Hotel,Bus,CalendarDays,Bell,Image,FileCheck,LogOut,RefreshCw,Search,CheckCircle} from 'lucide-react';
import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
async function req(path,opt={}){const token=localStorage.getItem('token');const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.message||'Request failed');return d}
function Login({onLogin}){const[e,setE]=useState('admin@conference.local'),[p,setP]=useState('Admin@123'),[busy,setBusy]=useState(false);const submit=async x=>{x.preventDefault();setBusy(true);try{const d=await req('/auth/login',{method:'POST',body:JSON.stringify({email:e,password:p})});localStorage.setItem('token',d.token);onLogin()}catch(err){alert(err.message)}finally{setBusy(false)}};return <div className="login"><form onSubmit={submit}><div className="brand">DPU</div><h1>Conference Control Room</h1><p>Manage participants, accommodation, transport and the entire event.</p><input value={e} onChange={x=>setE(x.target.value)} placeholder="Email"/><input type="password" value={p} onChange={x=>setP(x.target.value)} placeholder="Password"/><button disabled={busy}>{busy?'Signing in...':'Sign in'}</button><small>Demo: admin@conference.local / Admin@123</small></form></div>}
const menu=[['Dashboard',LayoutDashboard],['Participants',Users],['Accommodation',Hotel],['Transport',Bus],['Schedule',CalendarDays],['Notices',Bell],['Gallery',Image],['Certificates',FileCheck]];
function App(){const[logged,setLogged]=useState(!!localStorage.getItem('token'));const[tab,setTab]=useState('Dashboard');if(!logged)return <Login onLogin={()=>setLogged(true)}/>;return <div className="app"><aside><div className="sidebrand">DPU <span>Conference</span></div>{menu.map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I size={18}/>{n}</button>)}<button className="logout" onClick={()=>{localStorage.clear();setLogged(false)}}><LogOut size={18}/>Sign out</button></aside><main><header><div><h2>{tab}</h2><p>100th DPU AIU VC Conference 2026</p></div><button className="icon" onClick={()=>location.reload()}><RefreshCw size={18}/></button></header>{tab==='Dashboard'?<Dashboard/>:tab==='Participants'?<Participants/>:tab==='Accommodation'?<Hotels/>:tab==='Transport'?<Vehicles/>:tab==='Schedule'?<Schedule/>:<Placeholder title={tab}/>}</main></div>}
function Dashboard(){const[s,setS]=useState(null);useEffect(()=>{req('/admin/stats').then(setS).catch(e=>alert(e.message))},[]);if(!s)return <div className="loading">Loading dashboard…</div>;const cards=[['Participants',s.participants,Users],['Checked In',s.checkedIn,CheckCircle],['Speakers',s.speakers,Users],['Sessions',s.sessions,CalendarDays],['Hotels',s.hotels,Hotel],['Rooms',s.rooms,Hotel],['Gallery Photos',s.photos,Image],['Certificates',s.certificates,FileCheck]];return <><section className="hero"><div><span>LIVE CONTROL ROOM</span><h1>Conference Operations</h1><p>Monitor your event from one place.</p></div><div className="heroStat">2026</div></section><div className="grid">{cards.map(([n,v,I])=><div className="stat" key={n}><I/><span>{n}</span><strong>{v}</strong></div>)}</div><div className="panel"><h3>Operational checklist</h3><div className="checkgrid"><div>✓ Registration</div><div>✓ Accommodation</div><div>✓ Transport</div><div>✓ Session schedule</div><div>✓ Notifications</div><div>✓ Certificates</div></div></div></>}
function Participants(){const[d,setD]=useState([]),[q,setQ]=useState('');const load=()=>req('/admin/participants?conferenceId=1').then(setD).catch(e=>alert(e.message));useEffect(load,[]);const filtered=d.filter(x=>`${x.name} ${x.email} ${x.registration_no}`.toLowerCase().includes(q.toLowerCase()));return <div className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search participants"/></div><button onClick={load}>Refresh</button></div><table><thead><tr><th>Registration</th><th>Name</th><th>Category</th><th>Status</th><th>Payment</th><th>Action</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.registration_no}</td><td><b>{x.name}</b><br/><small>{x.email}</small></td><td>{x.category}</td><td><span className="pill">{x.status}</span></td><td>{x.payment_status}</td><td><select value={x.status} onChange={async e=>{await req(`/admin/participants/${x.id}/status`,{method:'PUT',body:JSON.stringify({status:e.target.value})});load()}}><option>PENDING</option><option>APPROVED</option><option>CHECKED_IN</option><option>CANCELLED</option></select></td></tr>)}</tbody></table></div>}
function Hotels(){const[d,setD]=useState([]);useEffect(()=>{req('/admin/hotels').then(setD).catch(e=>alert(e.message))},[]);return <div className="panel"><h3>Accommodation Overview</h3><table><thead><tr><th>Hotel</th><th>Address</th><th>Rooms</th><th>Capacity</th><th>Occupied</th></tr></thead><tbody>{d.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.address}</td><td>{x.rooms}</td><td>{x.capacity}</td><td>{x.occupied}</td></tr>)}</tbody></table></div>}
function Vehicles(){const[d,setD]=useState([]);useEffect(()=>{req('/admin/vehicles').then(setD).catch(e=>alert(e.message))},[]);return <div className="panel"><h3>Transport Fleet</h3><table><thead><tr><th>Vehicle</th><th>Type</th><th>Capacity</th><th>Driver</th><th>Phone</th><th>Status</th></tr></thead><tbody>{d.map(x=><tr key={x.id}><td><b>{x.vehicle_number}</b></td><td>{x.vehicle_type}</td><td>{x.capacity}</td><td>{x.driver_name||'Unassigned'}</td><td>{x.driver_phone||'—'}</td><td><span className="pill">{x.status}</span></td></tr>)}</tbody></table></div>}
function Schedule(){const[d,setD]=useState([]);useEffect(()=>{req('/sessions?conferenceId=1').then(setD).catch(e=>alert(e.message))},[]);return <div className="panel"><h3>Event Schedule</h3>{d.map(x=><div className="rowcard" key={x.id}><div className="time">{x.start_time}</div><div><b>{x.title}</b><p>{x.session_date} · {x.end_time} · {x.hall_name||'Hall'} · {x.speaker_name||'Speaker'}</p></div></div>)}</div>}
function Placeholder({title}){return <div className="panel empty"><h2>{title}</h2><p>This module is represented in the database/API and is ready for CRUD screens, file upload and role-specific workflows.</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
